### ISSUE TITLE
Group Finder: Search/Cancel Buttons in Results View are Extremely Difficult to Tap

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1001]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Execute a tag search in Group Finder.
2. Attempt to tap the magnifying glass to add a query.

- or -

1. Execute a query search in Group Finder.
2. Attempt to tap `Cancel` to remove the query.

### Buggy Behavior

Magnifying Glass/Cancel action doesn't execute unless you hit the incredibly small target area for the actionable UI.

### Expected Behavior

Action should execute when the icon/word is tapped, consistently.

**Comment by johnthepink** [comment]
I wonder if that icon should be bigger in general on mobile. @samclaridge

**Comment by samclaridge** [comment]
I don't think the icon should be bigger as it's not meant to be a primary interaction point. I think we should for sure look into making the tap targets bigger though to compensate for touch interactions.
