### ISSUE TITLE
Group Finder: Group Profile Meeting Time Format is Incorrect

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1003]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Execute a search in Group Finder.
2. View Group Profile

### Buggy Behavior

Meeting time format reads `07:30 PM`

### Expected Behavior

Leading zero should not be present. Example: `7:30 PM`

### Screenshots

![img_0008](https://cloud.githubusercontent.com/assets/2465823/18489817/40953458-79cd-11e6-9ebd-554f614425dc.PNG)

**Comment by jbaxleyiii** [comment]
This is a bug in heighliner. I'll fix it tonight

**Comment by jbaxleyiii** [comment]
fixed with https://github.com/NewSpring/Heighliner/pull/194
