### ISSUE TITLE
Group Finder: Edited Message in Group Onboarding is not Visible

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1005]
## Steps to Reproduce

Describe how to reproduce this issue.

1. View any Group Profile
2. Tap "Join Group"
3. Attempt to Edit Message

### Buggy Behavior

When I select the pre-populated text and try to type my own, the text is not visible.

### Expected Behavior

Edited content in message field should be visible as text is added.

### Screenshots

Message field, prior to editing:
![img_0009](https://cloud.githubusercontent.com/assets/2465823/18490589/a18aa2f4-79d0-11e6-8cb3-ddd128212f20.PNG)

Message field populated with a custom message:
![img_0010](https://cloud.githubusercontent.com/assets/2465823/18490591/a45d4220-79d0-11e6-91eb-0a4ff5f67dc5.PNG)

Message field with a custom message, on blur.
![img_0011](https://cloud.githubusercontent.com/assets/2465823/18490595/a74461b2-79d0-11e6-9939-a3d69542ffd6.PNG)

**Comment by jbaxleyiii** [comment]
> I think there's room to make it more clear that this message is editable. I'm not convinced the border below the textarea communicates that it is in fact a field that can be edited. 

Since this isn't a bug, I don't think it should be part of this issue. Can you open another issue with those concerns and tag is as `suggestion` or `enhancement?

@jakedawkins can you take a look at the rest?

**Comment by briankalwat** [comment]
@jbaxleyiii I'd be glad to if you or @samclaridge think there's validity to it. Otherwise if you think it's fine as-is I'll just remove it and we'll move right along.

**Comment by samclaridge** [comment]
@briankalwat Yeah I definitely think it's something we could improve ++ for separate issue.

**Comment by johnthepink** [comment]
For all wanting to know, this was caused by

```
-webkit-user-select: none;
```

I reneabled this for textareas
