### ISSUE TITLE
Discover: Tapping the Magnifying Glass Should Probably Add Focus to Search Text Field

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1016]
## Suggestion

I don't think the magnifying glass is currently a trigger for entering text into the search field. This could probably be a helpful addition.

**Comment by johnthepink** [comment]
@cdanwards is taking a look at this!

**Comment by jbaxleyiii** [comment]
@cdanwards has a fix in place!

**Comment by cdanwards** [comment]
Fix included in PR #1115 !

**Comment by johnthepink** [comment]
closed by #1115
