### ISSUE TITLE
Group Finder: Add Clarity to Editability of Group Onboarding Message

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1017]
## Suggestion
I think there's room to make it more clear that this message is editable. I'm not convinced the border below the textarea communicates that it is in fact a field that can be edited.

**Comment by jbaxleyiii** [comment]
@briankalwat @samclaridge and I agree out text-area UI isn't as clear as it should be. As an intermediate solution while we think through improvements, I've added this:

<img width="310" alt="screen shot 2016-09-14 at 7 39 18 pm" src="https://cloud.githubusercontent.com/assets/4967600/18533703/f4bd211c-7ab2-11e6-8c98-f40179ab35c1.png">

**Comment by briankalwat** [comment]
@jbaxleyiii 🔥 🔥
