### ISSUE TITLE
Status bar not changing text color for isLight check

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#1022]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to a video with a light brand color

### Buggy Behavior

Text in the status bar stays white and is therefore not visible.

### Expected Behavior

Text in the status bar should respond to the isLight check and change to light or dark based on the brand color of the series.

### Screenshots

Screenshots of the issue are greatly appreciated.

**Comment by edolyne** [comment]
Also when navigating to a devotional from related content within a sermon the status bar does not change color.
