### ISSUE TITLE
Sermons: Header Bar Does Not Display Correctly

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1031]
## Steps to Reproduce

1. View any #ForSC sermon in the app.

### Buggy Behavior

Header bar is not displayed correctly.

### Expected Behavior

Header bar should be displayed in a manner consistent with the other sermons.

### Screenshots

![img_0012](https://cloud.githubusercontent.com/assets/2465823/18527312/42095a60-7a92-11e6-96c4-570dd9485294.PNG)

**Comment by johnthepink** [comment]
@briankalwat thanks! This was fixed in #1027 and should be included in a beta release either later today or first thing tomorrow. I'll close for now, but feel free to reopen if the next build doesn't fix the issue.
