### ISSUE TITLE
Sermon images forbidden

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#1032]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to /series
2. Scroll down a long way, almost to the bottom of the list.

### Buggy Behavior

A couple series are missing images, but have images associated with them in EE.
- Man vs Wife
- Practical Atheist 
- No Perfect People

In the console I am getting the forbidden error, which I had with the Difference Maker EP when the lambda function was timing out.

`http://drhztd8q3iayu.cloudfront.net/newspring/collection/series_newspring/v4.sermonseries.graphics.1to1.manvswife.large.jpg 403 (Forbidden)`

### Expected Behavior

Series should have images.

### Screenshots

![screenshot 2016-09-14 15 55 01](https://cloud.githubusercontent.com/assets/7452283/18527658/aa10ddf8-7a93-11e6-9e18-6ec8083f9c6a.png)

**Comment by johnthepink** [comment]
@samclaridge I'll fix these tonight

**Comment by johnthepink** [comment]
These should be updated
