### ISSUE TITLE
Sign In/Register: Active State on Tab UI Requires Touch to Update

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1033]
## Steps to Reproduce

1. Tap the profile tab
2. Enter an email not associated with an account. (will auto-switch to register)

### Buggy Behavior

After the auto-switch to register, the `Register` text does not have the active green color until the user touches the screen again. The same thing happens when you tap `Sign In`. This potentially could be related to the same issue we're having with tags in #803. This appears to be a universal issue with the tab UI. Persistent on the Profile as well.

### Expected Behavior

Active tab should always have the green, active state on the text.

### Screenshots

![img_0014](https://cloud.githubusercontent.com/assets/2465823/18527734/fc338efa-7a93-11e6-844a-cddad258abd1.PNG)

**Comment by jbaxleyiii** [comment]
@briankalwat This is fixed in the next build 🎉
