### ISSUE TITLE
Tapping the status bar doesn't bring you back to the top of the feed (Nexus 7)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1036]
## Steps to Reproduce

1. Go to the home feed.
2. Scroll down a little way.
3. Tap the status bar

### Buggy Behavior

If I scroll down the feed some and then tap the status bar, I am not brought back to the top of the feed.

### Expected Behavior

If I tap the status bar I should be brought back to the top of the feed.

**Comment by jbaxleyiii** [comment]
@richarddubay sadly no android device does this 👎
