### ISSUE TITLE
Profile: Updating Photo Does Not Work

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1037]
## Steps to Reproduce

1. Go to your profile.
2. Tap your photo and attempt to upload/take a new photo.

### Buggy Behavior

Photo is not updated in the profile or on Rock.

### Expected Behavior

Photo should be updated in the app as well as on Rock.

**Comment by jbaxleyiii** [comment]
@briankalwat this may be because of CORS with Rock! I'll take a look!
