### ISSUE TITLE
"Contact Us" doesn't go to workflow (Nexus 7)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1038]
## Steps to Reproduce

1. Search for a group
2. Click the "Contact Us" button
3. Watch it do nothing

### Buggy Behavior

Clicking the "Contact Us" button doesn't go to the workflow.

### Expected Behavior

Clicking the "Contact Us" button should go to the workflow.

**Comment by jbaxleyiii** [comment]
Need to fix this!

**Comment by jonhorton** [comment]
Confirmed this on Galaxy S4, S5 and Nexus 5x!

**Comment by johnthepink** [comment]
In case we see this again in the future, we have a catch all event listener for clicks on the document, if it's an `<a>` tag, it tries to use either the iOS or Android in app browser. But, on Android event listeners added to the document on Meteor.startup don't ever seem to get added. I added this to our Global react component on componentWillMount to ensure the event listener gets added.
