### ISSUE TITLE
Can't give with a saved account on native device

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzmann#1041]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Open giving in app
2. Give with a saved account
3. Watch it spin forver

### Buggy Behavior

The spinner just spins and spins. Not sure if it actually gave

### Expected Behavior

Success screen should show and gift should go through

**Comment by jonhorton** [comment]
@jbaxleyiii This was working at 5pm, but I'm confirming it's not working on the S5 now. Was there a change? (or maybe this bug didn't affect the beta app?)

**Comment by jonhorton** [comment]
This bug is also affecting scheduling a gift.

FWIW, It seems to work great in the beta app and only is a bug on the current alpha build. A regression maybe?
