### ISSUE TITLE
Text promo links don't work correctly (Nexus 7)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1042]
## Steps to Reproduce

1. Tap the Fuse promo and it takes you back to the app main page
2. Tap the Information About Serving promo and it doesn't go anywhere.
3. This works correctly on the iPad Air.

### Buggy Behavior

Promo links don't open the in-app browser and take you to the right page.

### Expected Behavior

Promo links open the in-app browser and take you to the right page.

**Comment by jbaxleyiii** [comment]
@johnthepink any idea why this would only fail on android?

**Comment by johnthepink** [comment]
@jbaxleyiii I think those links need the inAppLink action associated with them. that was the fix i did for "contact us" in groups, but I have no idea if it fixed it. I'll add this to the other PR, and then start up the android sim

**Comment by jbaxleyiii** [comment]
@johnthepink ❤️

**Comment by jonhorton** [comment]
@johnthepink These text links work now, but One of the links points to giving which open in the in-app browser instead of in the app.  Is there a trick to have in-app links open within the app?

**Comment by samclaridge** [comment]
@jon we want to get to that eventually but it's going to be more complicated. John mentions it here #658

**Comment by richarddubay** [comment]
@jonhorton in the meantime we could remove that as a promo?

**Comment by jonhorton** [comment]
Thanks for the clarity @samclaridge! @richarddubay I think that's a great idea. Would you or someone on your team mind handling that?

**Comment by richarddubay** [comment]
@jonhorton on it.
