### ISSUE TITLE
Not showing saved accounts (iPad Air) (Nexus 7) (iPhone 6S)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1045]
## Steps to Reproduce

1. Sign in to your profile in the app on an iPad Air.
2. Go to Settings
3. Click on Saved Accounts
4. See your saved accounts.
5. Click the back arrow.
6. Click on Saved Accounts again.
7. See that it doesn't show your saved accounts.

### Buggy Behavior

Saved payment accounts are not showing correctly if I leave the saved payment accounts screen and then try to go back in again.

### Expected Behavior

Saved payment accounts should always show.

**Comment by jbaxleyiii** [comment]
@richarddubay nice! this is fixed by #1043
