### ISSUE TITLE
Series trailers ends with a "c" in the middle of the video window (Nexus 7) (iPad Air)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1050]
## Steps to Reproduce

1. Go to watch the trailer for the I Am series.
2. Watch it until it ends.
3. A "c" shows in the video window when it's done.

### Buggy Behavior

A "c" displays in the video window after the trailer finishes playing.

### Expected Behavior

I'm guessing something other than a "c" (probably a play button) should show in the video window.

### Screenshots

![1431690564377449059-account_id 2](https://cloud.githubusercontent.com/assets/3229463/18533992/40654afc-7ab5-11e6-8be5-75c6616a9395.png)

**Comment by jonhorton** [comment]
@richarddubay @jbaxleyiii For this one, in addition to fixing the "c", could this just auto close the trailer?

**Comment by jbaxleyiii** [comment]
@jonhorton what would auto close the trailer?

**Comment by johnthepink** [comment]
@jonhorton @jbaxleyiii i thought i fixed this. guess not. i would think auto closing is possible on video end for android, but this probably won't be possible on iOS phones, since they go full screen right now.
