### ISSUE TITLE
Links don't work in articles (Nexus 7)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1051]
## Steps to Reproduce

1. Click on an article. I used "What is Fasting and Why Do Christians Do It?"
2. Click a link.
3. Watch it do nothing.

### Buggy Behavior

Clicking links doesn't work in articles.

### Expected Behavior

Links should open an in-app browser to the linked content.

* This might be the same issue as the links in the Discover section, but thought I'd note it anyway.

**Comment by jonhorton** [comment]
This issue also appears in devotions (maybe safe to say all content types?)

Within devotionals, if you click on the scripture tab, the copyright links at the bottom also exhibit the same behavior.

**Comment by jonhorton** [comment]
This also affects the terms of use link when registering.

**Comment by johnthepink** [comment]
@jonhorton all links across the app that are external should be fixed by #1058

**Comment by jonhorton** [comment]
CONFIRMED AND YAY!
