### ISSUE TITLE
Playing video while audio is playing should stop audio

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1054]
This will most likely be resolved with playlist support, but worth adding here anyway since it's not a great experience. I think it'd be ideal to resolve sooner if possible.

## Steps to Reproduce

1. Play audio from either a music album or sermon audio
2. Find a sermon and play the video or trailer

### Buggy Behavior

The video plays on top of the currently playing audio.

### Expected Behavior

The currently playing audio should pause once a video begins to play

**Comment by jbaxleyiii** [comment]
@jonhorton @delianides agrees ;) He has been bugging me about this haha

**Comment by jbaxleyiii** [comment]
Fixed 💯
