### ISSUE TITLE
Clicking Go from an input field should hide the keyboard

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1055]
## Steps to Reproduce

This may be more apparent on smaller screen resolutions, but it's not a great experience nonetheless. This was tested on android.

1. Visit group finder and search for a tag
2. from the results page, click the search icon
3. type a keyword and click go on the keyboard.

### Buggy Behavior

While the search performs properly, the keyboard stays active, hiding any of the loading animation or new search results.

### Expected Behavior

Keyboard should auto hide so that the user can immediately take action. 

My suggestion is that this becomes the common event on any input/search actions.

**Comment by jbaxleyiii** [comment]
@jonhorton @johnthepink any idea what even the `go` button triggers?

**Comment by jonhorton** [comment]
Additionally, on the S5, there isn't a hide keyboard icon visible, making this a more difficult experience for the users.

**Comment by jonhorton** [comment]
@jbaxleyiii Doesn't it trigger the submit action on the input field?

**Comment by jbaxleyiii** [comment]
@jonhorton input's don't actually have a submit action. I don't think it triggers a blur either. I think it just tries to go to the next input

**Comment by jonhorton** [comment]
@jbaxleyiii  hmm... I'm not going to be able to help you with that event then. I humbly defer to @johnthepink's wisdom.

**Comment by jbaxleyiii** [comment]
haha no worries! I'll do some digging after the critical bugs are closed!

**Comment by jbaxleyiii** [comment]
we should be able to add `type=submit` to the input form and that should close the keyboard. Need to test

**Comment by johnthepink** [comment]
@jbaxleyiii i've fixed this before by unfocusing the input on the click event

**Comment by johnthepink** [comment]
you can also add some attributes to get the keyboard to say "Search" instead of "go". i'll fix this
