### ISSUE TITLE
Watch live banner color looks weird against brand green on annual report

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1057]
This is more of a suggestion / guideline that we should develop.

If you visit the annual report page while the watch live banner is present, it looks weird since the top header section is primary green, banner is secondary and then the main page is back to primary green.

Does it make sense to create a guideline that says the initial background of a page shouldn't be primary green? That would prevent it from conflicting with the header + banner.

**Comment by jbaxleyiii** [comment]
@jonhorton one of the thoughts is to potentially move the watch live banner ABOVE the header and change the status bar color to match it when live. If we do this we would need to figure out a way to match the color change of watch live but it solves this issue plus oddities on series when live.

**Comment by jbaxleyiii** [comment]
closing for #1086 which I think will be the right solution

cc @samclaridge
