### ISSUE TITLE
Fund should be auto selected when visiting a giving campaign page

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1065]
## Steps to Reproduce

1. Visit Give Now > Click a campaign page
2. Scroll down to the give component

### Buggy Behavior

The fund dropdown is blank instead of being prefilled.

### Expected Behavior

The Select fund dropdown should auto select the current campaign since it's the only available option on a campaign page.

**Comment by jonhorton** [comment]
Additionally, I think the "and give to" feature should not display on a campaign page since it's impossible to add another campaign in this context.

**Comment by jbaxleyiii** [comment]
hmmm, this is a regression. Thanks for reporting!

**Comment by jonhorton** [comment]
That's what I had thought!
