### ISSUE TITLE
Double tapping the home icon should scroll the home feed to the top

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1067]
I think a nice feature for both Android + iOS would be to add an action that resets the home feed when a user double taps the home icon. A nice scroll up animation could be nice.

Thoughts?

**Comment by jbaxleyiii** [comment]
@jonhorton we had this at one point, and it caused some issue with rendering the nav. It's worth uncommenting and trying again though!

Its a great feature!
