### ISSUE TITLE
Can't add spaces to a saved payment account name

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1088]
## Steps to Reproduce

1. Visit Give > Give Now
2. Don't have a saved account on file
3. Go through the process to add your first payment account
4. Try to type spaces in the Saved Account Name field

### Buggy Behavior

Spaces simply do not register

### Expected Behavior

Spaces should work properly (like they used to)

**Comment by jbaxleyiii** [comment]
@jonhorton can you show me this? I can't seem to duplicate

**Comment by jonhorton** [comment]
@jbaxleyiii Yep!

**Comment by jonhorton** [comment]
Closing this out as I can't replicate on 3 devices with the last build. :heart:
