### ISSUE TITLE
Adding a profile image doesn't take

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1089]
## Steps to Reproduce

1. Visit the profile page
2. Tap the placeholder icon and upload a new one
3. Observe the new image in place
3. Tap into another section then go back to the profile

### Buggy Behavior

After leaving then returning to the profile page, the old placeholder image is still there instead of the newly uploaded image

### Expected Behavior

Profile image should be uploaded. If there is still uploading happening in the background, the user should be aware they need to wait before leaving the profile page.

**Comment by jbaxleyiii** [comment]
@jonhorton this was fixed with https://github.com/NewSpring/Holtzmann/pull/1047

**Comment by jonhorton** [comment]
@jbaxleyiii should I reopen this?
