### ISSUE TITLE
Can't upload a profile image on S4

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1090]
This may be related to #1089 

## Steps to Reproduce

This only happens on the Galaxy S4

1. Visit the profile page
2. Tap the profile image
3. Try to add an image using the camera action
4. Try to add an image from and existing image on the phone (document)

### Buggy Behavior

Regardless of the method used, an image doesn't upload. Nothing happens.

### Expected Behavior

An image should upload using the selected method

**Comment by jbaxleyiii** [comment]
Fixed with https://github.com/NewSpring/Holtzmann/pull/1047
