### ISSUE TITLE
Profile: Updating Nickname field doesn't save

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1091]
## Steps to Reproduce

1. Visit Profile > Settings > Personal Details
2. Type in a new nickname
3. Click Update
4. Observe the success screen
5. Visit the Rock profile (in Rock) and observe that the nickname is in fact updated.

### Buggy Behavior

When going back to the Profile screen, the nickname is not being used.
When going back to the person details screen, the nickname is not updated
Even though rock is updated

### Expected Behavior

The app should instantly reflect the profile changes.

### Screenshots

Screenshots of the issue are greatly appreciated.

**Comment by jonhorton** [comment]
This is also happening for the Campus field. Perhaps this is a regression?

**Comment by jbaxleyiii** [comment]
@jonhorton it seems like a caching issue with heighliner / us pulling new data
