### ISSUE TITLE
Tags not returning to their initial state (color, size etc) after deselecting them. (Reported by Markie)

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzmann#1092]
iPhone 6 – Reported by Markie 

1. Go to group finder. 
2. Click on tags. 
3. Deselect tag. 

Buggy Behavior – Tags not returning to their initial state (color, size etc) after deselecting them. They lose the x but stay green.

Expected Behavior – Tags should return their normal state of gray and no x.

**Comment by samclaridge** [comment]
duplication of #803
