### ISSUE TITLE
Join a Group message shows when you sign in

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1095]
## Steps to Reproduce

1. Go to Group Finder
2. Select a tag or search for a group.
3. Pick a group you'd like to join.
4. Click "Join Group".
5. The sign in slider open. Click the "X" to close.
6. Go do anything else you want...it doesn't even matter.
7. Click on profile and sign in.
8. It shows the Request to Join a Group message. 

### Buggy Behavior

I've chosen to not sign in when I was interested in joining the group originally, but yet the system remembers that I clicked it when I try to sign in later, it shows me the request. Even if I don't want it to.

### Expected Behavior

Since I chose to not sign in when I was requesting to join the group originally, it should forget that I wanted to join the group.

**Comment by jbaxleyiii** [comment]
fixed by @JakeDawkins
