### ISSUE TITLE
Can't register for an account with an existing profile

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1104]
## Steps to Reproduce

1. Open the app and click the profile button to register
2. Try to register using an email address that is attached to a profile, but not a user account
(I was using a newspring.cc account: web+admin@newspring.cc)
3. Press Enter

### Buggy Behavior

Nothing happens on pressing enter button

### Expected Behavior

Should sign it or error out

FWIW, this worked on a completely new account with no rock profile

**Comment by jbaxleyiii** [comment]
@jonhorton I can confirm this is an issue with the `+` in the name. Will see if I can fix it

**Comment by jbaxleyiii** [comment]
This is an issue with Rock 👎 it errors out on a `+`. I'm going to close this for now and open up a few other issues related to it in various repos
