### ISSUE TITLE
Devotionals: Scripture section has indefinite loader

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1107]
## Steps to Reproduce

1. Open the app and load a devo
2. Click the scripture tab
3. Observe

### Buggy Behavior

The scripture itself never loads (the chapter/verse title is present) and the spinning animation shows indefinitely.

This happens on every devo I tested.

### Expected Behavior

Scripture should load.

**Comment by samclaridge** [comment]
I think this is a duplication of #730

**Comment by jonhorton** [comment]
@samclaridge Would this be the same issue when it was working with the last build?

**Comment by johnthepink** [comment]
I can't duplicate this on the latest beta

**Comment by jbaxleyiii** [comment]
Neither can I. I think it may be an issue with dropping connection and / or the api for the bible site missing

👍 for when this moves to heighliner
