### ISSUE TITLE
Native Player Repeat

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzmann#1110]
## Steps to Reproduce

Not totally sure how to reproduce. Something like

1. Start music
2. Hit repeat on full player
3. Song ends
4. App crashes

### Buggy Behavior

crashing

### Expected Behavior

non crashing

**Comment by johnthepink** [comment]
This also just happened for me after playing through several songs, and got to the end of the third song. So it probably has something to do with going to the next song.

**Comment by delianides** [comment]
is there a distinction between `repeat-one` or `repeat-all`? if its just `repeat-all` i still think its only about going to the next song.

**Comment by johnthepink** [comment]
repeat-one repeats the song you are currently on. repeat-all repeats the whole album when it's over

**Comment by delianides** [comment]
@johnthepink haha, i know that. I meant are there issues with just repeat-all or just repeat-one, or are they both affected.

**Comment by johnthepink** [comment]
@delianides i'm not s ure
