### ISSUE TITLE
Native Player Auto Play

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzmann#1111]
## Steps to Reproduce

Native player doesn't seem to audio play audio now.

1. Click album track or sermon audio

### Buggy Behavior

Audio doesn't start right away. I have to click play.

### Expected Behavior

Starts right away.

**Comment by jbaxleyiii** [comment]
@johnthepink should be fixed in the latest push of that branch

**Comment by johnthepink** [comment]
confirmed
