### ISSUE TITLE
Giving in app locks up after attempting to give once

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1124]
## Steps to Reproduce

1. Sign in to your account.
2. Attempt to give. This transaction should work just fine.
3. Attempt to give again. The app should not allow you to do anything. On iOS the "Complete Gift in Browser" and "X" buttons are frozen.

### Buggy Behavior

After giving once, you cannot give again because the app freezes. 

### Expected Behavior

I can give as many times as I want to without the app freezing.

**Comment by jbaxleyiii** [comment]
Fixed via #1127
