### ISSUE TITLE
No HCP causes a home feed refresh to not be persistent

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#1132]
## Steps to Reproduce

Since disabling hot code pushes, the home feed is now stuck at the state of that build. I can pull to refresh and it updates, but leaving the feed and coming back resets it. I only see this on iOS.

1. On iOS open the app and use the feed.
2. Wait until another post is published
3. View the feed
4. Refresh the feed (and note the new entries)
5. Visit another section (Like profile or sections)
6. Return to the feed

### Buggy Behavior

The new entries that appear upon refresh are no longer present when navigating back to the feed.

### Expected Behavior

The refreshed items (or any changes) should 
1. appear automatically after a period of time 
2. persist after refreshing

**Comment by johnthepink** [comment]
Hmm I wonder if this has to do with hot code push, or if new items aren't being properly placed in the client store on pull to refresh in general.

**Comment by jonhorton** [comment]
@johnthepink I was assuming hot code push since I have never seen this until we disabled it, but it could be anything :) 

It is odd that it only seems to be present on iOS.

**Comment by jonhorton** [comment]
Closing this as I haven't seen it happen in the past month!
