### ISSUE TITLE
Disabled prop on Checkboxes doesn't work

### ISSUE THREAD

**Issue by JakeDawkins** [NewSpring/Holtzmann#1134]
### Buggy Behavior

1. In the checkbox component (/imports/components/forms/Checkbox.js), the disabled function errors out because "disabled" isn't defined

### Expected Behavior

Passing in the "disabled" prop to the component should disable the checkbox. Not passing the component should leave the checkbox enabled.

**Comment by johnthepink** [comment]
closed by #1135
