### ISSUE TITLE
Music Player: Skipping Multiple Songs Crashes App & Prevents Relaunch

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1151]
## Steps to Reproduce

1. Play a song in the music player.
2. Skip multiple songs in rapid succession.

### Buggy Behavior

App crashes and cannot be relaunched.

### Expected Behavior

Songs should be able to be skipped.

**Comment by briankalwat** [comment]
This is limited to iOS only. Confirmed on iOS 9 & 10.

**Comment by delianides** [comment]
Fixed in 5.0.3

**Comment by jbaxleyiii** [comment]
@delianides @briankalwat this is actually in the 5.0.2 build which is currently in beta
