### ISSUE TITLE
Next & Previous buttons have to be tapped twice (Android)

### ISSUE THREAD

**Issue by richarddubay** [NewSpring/Holtzmann#1208]
## Steps to Reproduce

1. Play a song from an album.
2. Press the next button. The music stops, but nothing else happens.
3. Press the next button again. The next song starts to play.
(This happens with the previous button as well)

### Buggy Behavior

When trying to skip tracks using the next and previous buttons I have to click the button twice in order for the track skipping action to take place.

### Expected Behavior

I should only have to tap the button once for it to work.

**Comment by jbaxleyiii** [comment]
@richarddubay is this only s4? (not all android?)

**Comment by richarddubay** [comment]
@jbaxleyiii I had to wait for the S5 to charge and update itself (smh) before I could really test it. But yeah, S5 too. So I'm going with all Android here.

**Comment by jbaxleyiii** [comment]
@delianides  can you take this this afternoon?
