### ISSUE TITLE
Group Finder graphql 400 response

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzmann#1291]
```"Unknown argument "campuses" on field "groups" of type "Query". Did you mean "campus"?"```

**Comment by delianides** [comment]
```
{errors: [{message: "Variable "$excludeChannels" of required type "[String]!" was not provided.",…}]}
errors :[{message: "Variable "$excludeChannels" of required type "[String]!" was not provided.",…}]
```

**Comment by edolyne** [comment]
It appears that taking the brackets around String out, and changing the query to Campus fixes some of the issues.  This might be a symptom of a different problem though.

**Comment by edolyne** [comment]
Currently a WIP [fix-groupFinder](https://github.com/NewSpring/Holtzmann/tree/fix-groupFinder)
