### ISSUE TITLE
Audio Scrub Bar Not Aligned With Touch

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzmann#1332]
## Steps to Reproduce

This bug is present in iOS on iPad
1. Start playing an audio track
2. Move the scrub bar
### Buggy Behavior

The scrub bar position is far right of where your finger is on screen
### Expected Behavior

Scrub bar position closely follows your fingers position on screen.

**Comment by johnthepink** [comment]
i believe this is fixed now
