### ISSUE TITLE
Settings Edits: Info won't save on Iphone 6+ 5.0.3

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzmann#1349]
## Steps to Reproduce
1. Go to your Profile in the 5.0.3 app version
2. Click the settings icon in the upper right corner 
3. Go to "My Address" under settings
4. Try editing your address & then click update. It should say that your info has been successfully updated (though, for me this is only a brief flash)
5. Leave the page, then come back. Here you will see the bug - that your info change did not save. 
### Buggy Behavior

Even though you change your address in the settings of your Profile, it does not save. 
### Expected Behavior

When you change that information, it should update without reverting back to old information (aka, it should save).

**Comment by johnthepink** [comment]
should be fixed by #1362. feel free to reopen
