### ISSUE TITLE
Article Page 5.0.3 (may be specific article more than bug): no related content for a specific article shown

### ISSUE THREAD

**Issue by morgansmithh** [NewSpring/Holtzmann#1350]
## Steps to Reproduce

1. Go to the Article feed to article "[What has God Called you to Do With Your Life](https://newspring.cc/articles/3-truths-to-help-you-make-a-difference)" 
2. Scroll to bottom. Where there should be "Related Content," there is none 

### Buggy Behavior

No "related content" to be found at the bottom of the page

### Expected Behavior

Should be related content found at the bottom of the article!

**Comment by jbaxleyiii** [comment]
@morgansmithh turns out there are no tags for this article :( so there won't be any related content. Thanks for reporting though!
