### ISSUE TITLE
Settings: My Address is not displaying Home Address

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#1354]
## Steps to Reproduce

Describe how to reproduce this issue.

1. View "My Address" in Settings

### Buggy Behavior

Previous address (most recently entered) is displayed instead of current home address.

### Expected Behavior

Current home address should be displayed, not the one that was most recently entered.

### Screenshots

![img_0030](https://cloud.githubusercontent.com/assets/2465823/19483524/a591227a-9522-11e6-9e40-e625682853bc.PNG)

![image](https://cloud.githubusercontent.com/assets/2465823/19483543/b8f9509e-9522-11e6-8b00-9a0f949b86ae.png)

**Comment by JakeDawkins** [comment]
This is an issue with caching on heighliner. It **should** fix itself after a day, but I'm unsure of how Rock updates primary addresses if they are both listed as home. Need to debug on Heighliner.

**Comment by briankalwat** [comment]
@JakeDawkins should we not leave this open while we're debugging until we're sure it's resolved?

**Comment by JakeDawkins** [comment]
@briankalwat I'm gonna open an issue in Heighliner :)

**Comment by briankalwat** [comment]
🌮  @JakeDawkins ++
