### ISSUE TITLE
Discover results don't show keyword after navigating away

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#695]
**Steps to Reproduce**
- Open the app and visit the discover section
- Search for your favorite keyword 
- Observe the nicely formatted results
- Visit another section in the app
- (Optional) Wait an hour and come back to the app
- Visit the discover section

**Buggy Behavior**
- The results from the previous search are shown, but the keyword is missing from the input field

I think that adding the keyword back, helps bring context back to this page, but I think it brings up some other things worth discussing.

- Should the discover section reset back to it's default state after a certain timeout?
- Should there be an easier way to cancel a search? (Currently, it's not possible)

**Comment by johnthepink** [comment]
I think yes on all fronts.

We definitely need to add a cancel button back in. We used to have one, and I thought we created an issue for it, but I can't seem to find it. Good catch.

We need to reset to the featured content, but I'm not sure what the best case for that would be. Either a timeout, or just when you navigate away from discover in general.

If we do go with a timeout, we for sure need to ensure the search term is persistent.

@samclaridge @jbaxleyiii thoughts on resetting search to default state?

**Comment by johnthepink** [comment]
- [ ] decide what to do about resetting search
- [ ] make search term persistent in header if necessary based on ^^
- [ ] add cancel button back in

**Comment by samclaridge** [comment]
@jbaxleyiii I think we should a do timeout of say 30 mins before it resets. I started adding the Cancel button back in, but I think it needs updates to the redux store, which I’m not sure how to do.

**Comment by johnthepink** [comment]
## Discussion Had

We will go with adding the cancel button in, and also clear all search results on unmount of the discover page.

**Comment by johnthepink** [comment]
Fixed by #962
