### ISSUE TITLE
Order of Discover promotions is not consistent with the site

### ISSUE THREAD

**Issue by jonhorton** [NewSpring/Holtzmann#696]
We currently use a plugin within EE called Low Reorder to manually set the order of homepage promotions. Promotions are the only place we use this, and it goes against the usual "the most recently published item is first." Can we update the discover feed to reflect that?

**Steps to reproduce**
- Open the app and visit Discover
- Observe the order of the recommended by NewSpring promotions
- Visit the newspring.cc homepage, and observe the order
- Compare the two
- You can also look at the NS:Promotions channel to view specific dates for clarity.

**Buggy behavior**
- The app orders promotions by reverse chronological, while the homepage is manually ordered (by internal priority)

**Comment by jbaxleyiii** [comment]
fixed 👍
