### ISSUE TITLE
Search icon no mouse pointer

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#793]
When you hover over the search icon on Group Finder the mouse pointer does not change to mouse hand

**Comment by johnthepink** [comment]
Just to clarify, the search icon being referred to is the magnifying glass icon on the right:

<img width="772" alt="screenshot 2016-09-08 14 50 43" src="https://cloud.githubusercontent.com/assets/816517/18362432/b5712884-75d3-11e6-8f02-1a8f75aa4e3d.png">

**Comment by samclaridge** [comment]
@johnthepink correct.

**Comment by edolyne** [comment]
@johnthepink thoughts of adding a clickable class to Junction which would handle the on hover?  Or are we just looking for a quick fix and write the css inline?

**Comment by johnthepink** [comment]
@edolyne i think we should just turn it from a <span> in to a <button>, which has the hover state we want by default
