### ISSUE TITLE
Tag deselect color

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#803]
Steps to reproduce:
* On a mobile device, or using the browser inspector to simulate a touch based device.
* Click to select 1 tag.
* Click again to deselect the tag.

Incorrect behavior:
* X correctly disappears, but the tag remains green.

Expected behavior:
* Tag should return to light-tertiary when it has been de-selected.

**Comment by johnthepink** [comment]
via @briankalwat 

![](https://cloud.githubusercontent.com/assets/2465823/18488257/a5e44026-79c6-11e6-8a8c-8cde205c5435.PNG)

![](https://cloud.githubusercontent.com/assets/2465823/18488278/b1bd74f8-79c6-11e6-9aba-eb3191ea2393.PNG)

**Comment by briankalwat** [comment]
This issue is also prevalent on the `...` tag in the results view. Just fwiw.

**Comment by colemanben** [comment]
This issue is the same on iPad Mini

**Comment by edolyne** [comment]
Issue appears to be that the app is still viewing the tag as being in a hovered state.  Touching outside of the tags removes the highlight.

**Comment by jonhorton** [comment]
I may be on an older build, but I'm seeing what @edolyne referenced 5 hours ago.
