### ISSUE TITLE
Production Builds

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzmann#827]
In order to ship the app, there may be a few things to do before we can ship to app stores.

- [x] ios screenshots/design assets
- [x] ios descripton/marketing content
- [x] ios cert signing/provisioning
- [x] android screenshots/design assets
- [x] android description/marketing content
- [x] android cert signing/provisioning
- [x] anything else?

**Comment by jbaxleyiii** [comment]
@johnthepink @samclaridge where are we on this?

**Comment by johnthepink** [comment]
@jbaxleyiii i think we still need to create them all? the certs and provisioning are good to go.

**Comment by samclaridge** [comment]
@jbaxleyiii my thought was to use the on-boarding images as the screenshots. Is marketing writing the copy for the description, I feel like that's more up their alley?

**Comment by johnthepink** [comment]
we are in production!
