### ISSUE TITLE
Series light/dark color switch

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#945]
We need to add the light/dark color switch for text and buttons for SeriesItems and for Series index.

**Comment by samclaridge** [comment]
<img width="345" alt="screenshot 2016-09-08 16 45 03" src="https://cloud.githubusercontent.com/assets/7452283/18366180/aac64922-75e3-11e6-8b49-d04fa67e2fbb.png">
<img width="347" alt="screenshot 2016-09-08 16 45 13" src="https://cloud.githubusercontent.com/assets/7452283/18366187/b0543520-75e3-11e6-8dc9-8b31d23a6b5c.png">

**Comment by johnthepink** [comment]
also, status bar text color

![unspecified](https://cloud.githubusercontent.com/assets/816517/18400983/405807b0-76a6-11e6-9d7c-2a04706d8a6c.png)

**Comment by richarddubay** [comment]
@johnthepink @samclaridge Also, when we're "live", the live bar kind of breaks up all of that in a not so good way.

![img_0783](https://cloud.githubusercontent.com/assets/3229463/18418661/8d57d00e-7818-11e6-93d4-f59911a519f2.png)

**Comment by johnthepink** [comment]
@richarddubay yea hopefully that will look more appropriate when we get the text color changed.

**Comment by richarddubay** [comment]
@johnthepink it's almost like if the title bar and image and everything else is going to be one color and the live bar is going to be always green then the live bar should live maybe _above_ everything else? the series color, break for green, back to series color thing feels weird. But I can wait to see what it looks like when the text color is changed to make that call. :)

**Comment by johnthepink** [comment]
@richarddubay good to know. It currently does that on all series pages when the live bar is enabled (and pretty much everywhere in the app). If we need to reconsider that, would you mind opening a separate issue so we can track it separately of the light/dark switch? ❤️
