### ISSUE TITLE
Locations Page Scroll

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzmann#952]
## Steps to Reproduce
This bug is present on native app

- Visit the locations page, and scroll through the locations
- Scroll to find your campus, and search for your closest campus

## Buggy Behavior
The list doesn't scroll back to the first card

## Expected Behavior
- After tapping return, you are scrolled back up to the list of campuses
- Campus list scrolls back to the closest campus

**Comment by jbaxleyiii** [comment]
@edolyne I'd call that a usability bug. It's not a critical one but not what the user expects or we want: bug

**Comment by jbaxleyiii** [comment]
closed with #977
