### ISSUE TITLE
Trailing commas

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Holtzmann#961]
I _think_ we have decided we are in favor of these. If so, can we add them to the lint? Is there a reason they aren't there now?

 I'd be happy to adjust eslint and open a PR fixing existing code.

**Comment by johnthepink** [comment]
Actually, there may be a couple things I'd like to propose. I shall make a more formal proposal.

**Comment by jbaxleyiii** [comment]
@johnthepink please propose away!

**Comment by johnthepink** [comment]
@jbaxleyiii I think I'm actually for using the airbnb defaults, and then just switch it to double quotes. I used it for launch, and I liked everything about their normal JS linting. I looked at their React rules just now, and I think I pretty much agree with everything there too.

**Comment by johnthepink** [comment]
I'm sure that will bring up a bunch of issues, but we are refactoring anyways :)

**Comment by jbaxleyiii** [comment]
@johnthepink I totally agree. Let's do it! Do you want to open a PR?

**Comment by johnthepink** [comment]
@jbaxleyiii will do

**Comment by johnthepink** [comment]
This is added in lintings-fix and will be merged soonish
