### ISSUE TITLE
[Discussion] static typing

### ISSUE THREAD

**Issue by jbaxleyiii** [NewSpring/Holtzmann#964]
Flow vs typescript

## Flow

1. Allows for incremental typing
2. Works with babel which we rely on
3. Works with eslint
4. Works great with react-native

## Typescript

1. Known entity
2. Incredible IDE integrations
3. Well supported
4. More type defs around

**Comment by johnthepink** [comment]
I need to do some more research on flow.

**Comment by jbaxleyiii** [comment]
I figured out a way to make ts work with babel so that is less of a concern. The questions left for me is react-native and eslint.

Tslint is great, but it doesn't have lint-fix which is incredible

**Comment by delianides** [comment]
> It’s much harder to find good quality and up-to-date typings for Flow and it lacks a good manager. The result is you will probably end up with many any type annotations when using third-party libraries.

This probably would get resolved with time and as the community grows (unless they use typescript).

---

// TypeScript
class Foo extends React.Component<FooProps, FooState> {}

// Flow - much more readable
class Foo extends React.Component {
  state: FooState;
  props: FooProps;
}

**Comment by johnthepink** [comment]
I mentioned this earlier, but I think from a build perspective typescript sounds like it will complicate things. Where flow would be incrementally adoptable, and shouldn't add another layer of building we have to do.

**Comment by johnthepink** [comment]
I think we have decided to go with Flow for now, so I shall close
