### ISSUE TITLE
Sermon Audio Player Does Not Work

### ISSUE THREAD

**Issue by edolyne** [NewSpring/Holtzmann#968]
## Steps to Reproduce
This bug is present on the web, and native versions of the app.  This bug is only present on sermon audio and not music.

- Visit an individual sermon
- Tap on "Listen To Audio"
- Audio does not play

### Buggy Behavior

When tapping on Listen To Audio, audio does not play and throws the following error:

`TypeError: undefined is not an object (evaluating '_store.actions.setPlaying')`

Related Sentry Error:
https://sentry.io/newspring-church/app/issues/158347220/

### Expected Behavior

Tapping on Listen To Audio plays the sermon audio.

**Comment by jonhorton** [comment]
@edolyne I tried to reproduce this on Android, but the audio did in fact play. Which native device did you experience this on?

**Comment by jbaxleyiii** [comment]
@jonhorton this may be on the monolith which hasn't been shipped to beta yet

**Comment by jonhorton** [comment]
@jbaxleyiii ohhh.... that's good to know! I'll hold off on testing/confirming these then!

**Comment by jbaxleyiii** [comment]
@jonhorton we are planning on shipping a beta tomorrow though 🎉

**Comment by jonhorton** [comment]
@jbaxleyiii I can't wait—shipping days are always fun 👯

**Comment by johnthepink** [comment]
@jonhorton @jbaxleyiii it is the monolith. The latest alpha on Hockey should produce the issue

**Comment by jbaxleyiii** [comment]
@johnthepink I think @jonhorton runs the beta

**Comment by johnthepink** [comment]
@jbaxleyiii @jonhorton i figured :). just wanted to confirm it was an issue. ❤️

**Comment by edolyne** [comment]
@jonhorton I was using iOS, are you running the hockey version of the app?

On Mon, Sep 12, 2016 at 8:31 PM James Baxley

<
mailto:James Baxley <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/johnthepink
I think
https://github.com/jonhorton
runs the beta

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/NewSpring/Holtzmann/issues/968#issuecomment-246537956
, or

**Comment by jbaxleyiii** [comment]
fixed #979
