### ISSUE TITLE
Pull to Refresh Animation

### ISSUE THREAD

**Issue by delianides** [NewSpring/Holtzmann#972]
![](https://drwdes-dropshare.s3.amazonaws.com/9OrPtjcw8F/Screen-Recording-2016-09-12-15-59-49.gif)

I'd like to open up for discussion to see if theres a better solution for the pull-to-refresh loading state. The NewSpring mark spinning the way it does just seems too weird. Since the animation is happening through CSS (I think), the frame rate maybe be an issue. Could there be a way for the drop to just turn to a circle when the window snaps back after the user pulls to refresh?

Just a suggestion but I'd love to see what other people think.

@NewSpring/holtzmann

**Comment by jonhorton** [comment]
The strangest part for me is the fact that the mark is off center when it rotates. Is that what you're referring to @delianides? 

I'm also open to using the standard circle animation that we use in other places, even though I think using the mark is still a fun addition. :)

**Comment by jbaxleyiii** [comment]
fixed with #978
