### ISSUE TITLE
Profile tabs lose green color when switching

### ISSUE THREAD

**Issue by JakeDawkins** [NewSpring/Holtzmann#976]
## Steps to Reproduce

**This may be fixed by a fix to [issues/803](https://github.com/NewSpring/Holtzmann/issues/803)**

1. Log in and go to the profile tab
2. Click the "Likes" or "Following" tab and observe color changes
3. tapping elsewhere on the page afterwards fixes this

### Buggy Behavior

The active tab is black, not the primary green color.

### Expected Behavior

The active tab should be green, not black.

### Screenshots

![image](https://cloud.githubusercontent.com/assets/9259509/18452506/1746c78e-7909-11e6-9b45-cb21afb9e627.png)

**Comment by jbaxleyiii** [comment]
fixed with #980
