### ISSUE TITLE
Locations: Section Hierarchy Question

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#995]
Not a bug, but what is the vision behind leading the locations page with the directory vs the search? To me it seems like searching would be a much more helpful experience than having to scroll through all of the campuses to find the one you're looking for - and that's assuming you know which campus you're looking for. Thoughts?

**Comment by jbaxleyiii** [comment]
@briankalwat this is a great point and actually one that we already changed! It should be on the next beta build!

https://github.com/NewSpring/Holtzmann/pull/977
