### ISSUE TITLE
Scripture Not Loading

### ISSUE THREAD

**Issue by samclaridge** [NewSpring/Holtzmann#997]
## Steps to Reproduce

Describe how to reproduce this issue.

1. Go to a devotional
2. Tap on scripture tab

### Buggy Behavior

Loading spinner never goes away, and scripture never loads.

### Expected Behavior

Loading spinner should disappear and the scripture should load.

Not sure if this is related to #730 ?

### Screenshots

<img width="345" alt="screenshot 2016-09-13 15 26 53" src="https://cloud.githubusercontent.com/assets/7452283/18488225/8e95ba76-79c6-11e6-81c8-2ee271d7a623.png">

**Comment by johnthepink** [comment]
@samclaridge this is because some code went missing for this in the monolith. alpha builds and local builds won't show scripture. i've got a task in jira to fix this issue this week

**Comment by johnthepink** [comment]
I've re-added the meteor method for now. We will add this to Heighliner in the future, so I will leave this open for now.

**Comment by johnthepink** [comment]
Actually, never mind. We have #730 for that.
