### ISSUE TITLE
Group Finder: Tapping Selected Tag Does Not Visually Deselect Until User Scrolls

### ISSUE THREAD

**Issue by briankalwat** [NewSpring/Holtzmann#998]
## Steps to Reproduce

1. Go to Group Finder.
2. Select a Tag.
3. Deselect a Tag without scrolling after deselecting said tag.

### Buggy Behavior

Green background color (visual selected state) on tag remains even after selected tag has been deselected (although it returns to grey unselected state once you scroll).

### Expected Behavior

Tag should immediately become grey again when it is deselected.

### Screenshots

After tag is selected:

![img_0005](https://cloud.githubusercontent.com/assets/2465823/18488257/a5e44026-79c6-11e6-8a8c-8cde205c5435.PNG)

After tag us deselected.

![img_0006](https://cloud.githubusercontent.com/assets/2465823/18488278/b1bd74f8-79c6-11e6-9aba-eb3191ea2393.PNG)

**Comment by samclaridge** [comment]
I think this is the same as #803 ?

**Comment by briankalwat** [comment]
@samclaridge yes it is, you can close this unless you want the screenshots.

**Comment by briankalwat** [comment]
@samclaridge this behavior also exists in the tag list for the `...` tag in the results view once you've searched, just fwiw.

**Comment by johnthepink** [comment]
@briankalwat i added your screenshots to the other issue. I'll close this one in favor of the other. Thanks so much!
